### ISSUE TITLE
не работает приложение

### ISSUE THREAD

**Issue by Lamfi** [IbremMiner837/Garena-Free-Fire-Settings#2]
предлагают пожаловаться на разработчике за плохое приложение, кучу рекламы...

**Comment by Lamfi** [comment]
недавно открыл приложение вылезла реклама 1xbet

**Comment by Lamfi** [comment]
да

**Comment by intbyte-100** [comment]
Есть, я сам добавил

**Comment by MilfHunter8856** [comment]
Все там есть, я из будущего

**Comment by KirboGames** [comment]
ребят, я думаю вы поняли, что надо его банить за такое...
